version: '3'

services:

    backend:
        image: node:12
        depends_on:
            - db_auth
            - db_data
        volumes:
            - ./:/usr/src/app
            - ./node_modules:/usr/src/app/node_modules
            - ./dist:/usr/src/app/dist
        working_dir: /usr/src/app
        command: sh -c 'npm run dev'
        environment:
            - VIRTUAL_HOST=localhost # Enviroment variable needed for nginx proxy
        ports:
            - "80:8080"
            - "8443:8443"
        networks:
            - koa_lan
        logging:
            driver: json-file
            options:
                max-size: "10m"

    db_auth:
        image: redis
        volumes:
            - auth:/data
        ports:
            - "26379:6379"
        networks:
            - koa_lan
        logging:
            driver: json-file
            options:
                max-size: "10m"

    db_data:
        image: mysql:5
        volumes:
            - data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: koatypescript
        command:
            - --max_allowed_packet=64M
        ports:
            - "23306:3306"
        networks:
            - koa_lan
        logging:
            driver: json-file
            options:
                max-size: "10m"

volumes:
    # node_modules:
    # dist:
    auth:
    data:

networks:
    koa_lan:
