version: '3'

services:

    backend:
        image: node:12
        depends_on:
            - db_auth
            - db_data
        volumes:
            - ./:/usr/src/app
            - node_modules:/usr/src/app/node_modules
            - dist:/usr/src/app/dist
        working_dir: /usr/src/app
        command: sh -c 'npm run prod'
        ports:
            - "8443:8443"
        logging:
            driver: json-file
            options:
                max-size: "10m"

    db_auth:
        image: redis
        volumes:
            - koa_db_auth:/data
        ports:
            - "26379:6379"
        logging:
            driver: json-file
            options:
                max-size: "10m"

    db_data:
        image: mysql:5
        volumes:
            - koa_db_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: koatypescript
        command:
            - --max_allowed_packet=64M
        ports:
            - "23306:3306"
        logging:
            driver: json-file
            options:
                max-size: "10m"

volumes:
    node_modules:
    dist:
    koa_db_auth:
    koa_db_data:
