version: '3'

services:

    backend:
        image: node:12
        depends_on:
            - db_auth
            - db_data
        volumes:
            - ./:/usr/src/app
            - ./node_modules:/usr/src/app/node_modules
            - ./dist:/usr/src/app/dist
        working_dir: /usr/src/app
        command: sh -c 'npm run prod'
        environment:
            - VIRTUAL_HOST=api.koa.pfouque.fr # Enviroment variable needed for nginx proxy
            - LETSENCRYPT_HOST=api.koa.pfouque.fr # Enviroment variables needed for Let's Encrypt companion
            - LETSENCRYPT_EMAIL=pfouque@gmail.com
        ports:
            - "80"
            - "8443:8443"
        networks:
            - nginx-proxy
        logging:
            driver: json-file
            options:
                max-size: "10m"

    db_auth:
        image: redis
        volumes:
            - auth:/data
        ports:
            - "26379:6379"
        networks:
            - nginx-proxy
        logging:
            driver: json-file
            options:
                max-size: "10m"

    db_data:
        image: mysql:5
        volumes:
            - data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: koatypescript
        command:
            - --max_allowed_packet=64M
        ports:
            - "23306:3306"
        networks:
            - nginx-proxy
        logging:
            driver: json-file
            options:
                max-size: "10m"

volumes:
    auth:
    data:

networks:
    nginx-proxy:
        external:
            name: webproxy_nginx-proxy # Reference webproxy/nginx-proxy container network 
