version: '3'

services:

    backend:
        image: node:12
        depends_on:
            - db_auth
        volumes:
            - ./:/usr/src/app
            - node_modules:/usr/src/app/node_modules
            - dist:/usr/src/app/dist
        working_dir: /usr/src/app
        command: sh -c 'npm install; npm run build; npm run prod'
        ports:
            - "8443:8443"
        logging:
            driver: json-file
            options:
                max-size: "10m"

    db_auth:
        image: redis
        ports:
            - "26379:6379"
        logging:
            driver: json-file
            options:
                max-size: "10m"

volumes:
    node_modules:
    dist:

